apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::980913156202:user/test           #arn:aws:iam::095420225348:user/github-ci
      username: test
      groups:
        - system:masters
